# Generated by Django 3.0.7 on 2021-03-11 02:49

from django.db import migrations, models
import user_management.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20200908_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='team_member', validators=[user_management.models.validate_image])),
                ('linkdinURL', models.URLField()),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
