# Generated by Django 3.0.7 on 2021-03-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_team_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ManyToManyField(blank=True, to='user_management.Team'),
        ),
    ]
