# Generated by Django 3.0.7 on 2021-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20210311_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
