# Generated by Django 3.0.7 on 2021-03-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20210311_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMember',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='Phase',
        ),
    ]
