# Generated by Django 3.0.7 on 2021-03-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_auto_20210318_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('-order',)},
        ),
    ]
