# Generated by Django 3.0.6 on 2020-06-06 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('access_token', models.UUIDField(default=uuid.uuid4)),
                ('description', models.TextField(max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_header')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
