# Generated by Django 3.0.7 on 2020-06-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200701_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
