# Generated by Django 3.0.7 on 2020-07-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200701_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_admin',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='project_header/default.png', null=True, upload_to='project_header'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, default='project_logo/default.png', null=True, upload_to='project_logo'),
        ),
    ]
