# Generated by Django 3.0.6 on 2020-06-06 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('date_modified', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='log.Logger')),
            ],
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='logfile')),
                ('filetype', models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('dwg', 'dwg'), ('misc', 'misc')], max_length=100)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='log.Logger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
