# Generated by Django 3.0.7 on 2020-06-11 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200610_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='log.Logger'),
        ),
    ]
