# Generated by Django 3.0.7 on 2020-06-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200612_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='filetype',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('pdf', 'pdf'), ('dwg', 'dwg'), ('misc', 'misc')], max_length=100, null=True),
        ),
    ]
