# Generated by Django 3.0.7 on 2020-06-11 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200612_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='is_encrypted',
            new_name='default_password',
        ),
    ]
