# Generated by Django 3.0.7 on 2020-06-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20200612_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='default_password',
            field=models.BooleanField(default=True),
        ),
    ]
