# Generated by Django 3.0.7 on 2020-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20200612_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='log.Tags'),
        ),
    ]
