# Generated by Django 3.0.7 on 2020-06-20 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0008_auto_20200612_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='user_access', related_query_name='user_access', to=settings.AUTH_USER_MODEL),
        ),
    ]
