# Generated by Django 3.0.7 on 2020-07-10 00:53

from django.db import migrations, models
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20200710_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logfile',
            name='log',
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file',
            field=models.FileField(upload_to=log.models.user_directory_path),
        ),
    ]
