# Generated by Django 3.0.7 on 2020-09-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200908_1742'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0012_auto_20200908_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='logger',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logurl',
            name='log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.Logger'),
        ),
    ]
