# Generated by Django 3.0.7 on 2020-06-09 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0002_auto_20200610_0208'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('logger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='log.Logger')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Project')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project.Team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
